export const ADD_POST = "ADD_POST";
export const DELETE_POST = "DELETE_POST";
export const EDIT_POST = "EDIT_POST";
export const TOGGLE_LIKE = "TOGGLE_LIKE";
export const TOGGLE_SAVE = "TOGGLE_SAVE";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const TOGGLE_LIKE_COMMENT = "TOGGLE_LIKE_COMMENT";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const LOAD_POSTS = "LOAD_POSTS";
export const LOAD_USERS = "LOAD_USERS";
export const LOAD_BOOKMARKS = "LOAD_BOOKMARKS";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const FOLLOW_TOGGLE = "FOLLOW_TOGGLE";

export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const LOAD_CONVERSATIONS = "LOAD_CONVERSATIONS";
export const LOAD_NOTIFICATIONS = "LOAD_NOTIFICATIONS";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const MARK_NOTIFICATION_READ = "MARK_NOTIFICATION_READ";
export const MARK_ALL_NOTIFICATIONS_READ = "MARK_ALL_NOTIFICATIONS_READ";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";

export const LOAD_ALBUMS = "LOAD_ALBUMS";
export const CREATE_ALBUM = "CREATE_ALBUM";
